# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3bc469ad539855f2d73995f2390343885b21ecb68a108b92afb6a7263fd43ea03d7a00f56be5278a412173ea01c4f8e4948a2b9f11ffe4c104bab01686f790a8

test:
  secret_key_base: 5f687d510bcbf0283772e2574619295966d2e4171ea43b500f9e18094500c0a9cfc56243e3bdf9ab04b0bbffed3f596c8c1a1b384124e3631550d6891cf32964

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
